# Generated by Django 3.2.8 on 2022-01-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_no',
            field=models.IntegerField(unique=True),
        ),
    ]
