# Generated by Django 3.2.8 on 2022-01-14 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_room_room_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='Departure',
            new_name='check_in_date',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='arrival_date',
        ),
    ]
